# Generated by Django 3.1.6 on 2021-05-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('ephno', models.IntegerField(max_length=10)),
                ('eexp', models.FloatField()),
                ('edob', models.DateField()),
                ('esal', models.IntegerField()),
            ],
        ),
    ]
