# Generated by Django 3.1.6 on 2021-05-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ephno',
            field=models.IntegerField(),
        ),
    ]
