# Generated by Django 3.1.6 on 2021-05-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0002_auto_20210529_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ephno',
            field=models.CharField(max_length=10),
        ),
    ]
