# Generated by Django 3.1.6 on 2021-05-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0003_auto_20210529_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ephno',
            field=models.CharField(max_length=15),
        ),
    ]
